#General settings
[general]
	#modpackProjectID is now deprecated and will be removed soon
	# Default: 0
	# Range: > 0
	modpackProjectID = 1134042
	#The name of the modpack
	modpackName = "ScaleCraft Chronicles Of The Arcane"
	#The version of the modpack
	modpackVersion = "0.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
